export const skills = {
	HTML5: "html",
	CSS3: "css",
	JavaScript: "js",
	React: "react",
	Redux: "redux",
	"Tailwind CSS": "tailwind",
	TypeScript: "ts",
	Python: "python",
	Django: "django",
	Flask: "flask",
	"Node.js": "nodejs",
	"REST APIs": "django",
	SQL: "mysql",
	MongoDB: "mongodb",
	PostgreSql: "postgresql",
	Git: "git",
	GitHub: "github",
	SQLite: "sqlite",
	Postman: "postman",
	Bitbucket: "bitbucket",
	Bootstrap: "bootstrap",
	Figma: "figma",
	Firebase: "firebase",
	"VS Code": "vscode",
	Azure: "azure",
	Docker: "docker",
	AWS: "aws",
};

export const skillsData = [
	{
		section: "Languages",
		skills: "Javascript, Python",
	},
	{
		section: "Specialities",
		skills: "React, Redux, Tailwind, Django, Django REST",
	},
	{
		section: "Databases",
		skills: "MySQL, PostgreSQL, MongoDB",
	},
	{
		section: "Deployment",
		skills: "AWS, Azure, Git",
	},
	{
		section: "Design",
		skills: "Figma, Adobe Photoshop",
	},
	{
		section: "Interests",
		skills: "Dogs, Photography, Hiking",
	},
];

export const portfolioData = [
	{
		id: 1,
		title: "The Neo Project",
		img: "neoProject.png",
		imgMobile: "neoProjectMobile.png",
		shortDescription: "Smart Search for Rescue Dogs",
		longDescription:
			"A fast, intuitive search platform that helps users discover rescue dogs using an optimized binary search system. Designed to make rehoming easier through clean UI, real-time filtering, and a friendly browsing experience.",
		languages: ["Django", "React", "Tailwind", "Typescript"],
		keyFeatures: ["Binary search algorithm"],
		link: "https://the-neo-project.web.app",
		linkText: "https://the-neo-project.web.app",
		github: "https://github.com/skies09/the-neo-project",
		additionalGithub: "https://github.com/skies09/neoProject",
		category: "app",
	},
	{
		id: 2,
		title: "Wiggles & Walks",
		img: "wigglesAndWalks.png",
		imgMobile: "wigglesAndWalksMobile.png",
		shortDescription: "Dog Walking Service Website",
		longDescription:
			"A warm and approachable website for a local dog walking business, built to showcase services, pricing, and brand personality while keeping user experience simple, friendly, and mobile-first.",
		languages: ["React", "Tailwind"],
		keyFeatures: [],
		link: "https://wiggles-and-walks.web.app",
		linkText: "https://wiggles-and-walks.web.app",
		github: "https://github.com/skies09/wiggles-and-walks",
		category: "website",
	},
	{
		id: 3,
		title: "Donna's Dog Photography",
		img: "donnaDogPhotography.png",
		imgMobile: "donnaDogPhotographyMobile.png",
		shortDescription: "Professional Dog Photography Portfolio",
		longDescription:
			"A vibrant and elegant portfolio site for a dog photography business, showcasing high-quality images with smooth navigation and a minimalist, modern layout tailored to highlight the photographer’s work.",
		languages: ["React", "Tailwind"],
		keyFeatures: [],
		link: "https://donna-dog-photography.web.app",
		linkText: "https://donna-dog-photography.web.app",
		github: "https://github.com/skies09/donna-dog-photography",
		category: "website",
	},
	{
		id: 4,
		title: "Apex Logistics",
		img: "apexLogistics.png",
		imgMobile: "apexLogisticsMobile.png",
		shortDescription: "Professional Driver Hire Platform",
		longDescription:
			"A clean, corporate-ready platform for a driver-hire logistics company. Built for clarity and trust, it highlights services, contact channels, and flexible driver-hire options through a polished React + TypeScript interface.",
		languages: ["React", "Typescript", "Tailwind"],
		keyFeatures: [],
		link: "https://apex-logistics-8efb4.web.app",
		linkText: "https://apex-logistics.web.app",
		github: "https://github.com/skies09/apex-logistics",
		category: "website",
	},
	{
		id: 5,
		title: "BuJo",
		img: "bujo.png",
		imgMobile: "bujoMobile.png",
		shortDescription: "All-in-One Digital Bullet Journal",
		longDescription:
			"A productivity app combining bullet journaling, day planning, and mind-mapping into a single streamlined interface. Designed for users who want structure and creativity in one place, with an intuitive workflow powered by Django and React. Mobile app coming soon.",
		languages: ["Django", "React", "Tailwind", "Typescript"],
		keyFeatures: [],
		link: "https://bu-jo-4ca96.web.app/",
		linkText: "https://bu-jo.web.app/",
		github: "https://github.com/skies09/bu-jo",
		additionalGithub: "https://github.com/skies09/Bujo",
		category: "app",
	},
];

export const testimonials = [
	{
		name: "Michael",
		role: "Head of business development",
		quote: "I'm really blown away by what she was able to develop in such a short period of time!",
		rating: 5,
	},
	{
		name: "Katie",
		role: "Project manager",
		quote: "Was able to put her own unique flair into components developed.",
		rating: 5,
	},
	// {
	// 	name: "Gareth",
	// 	role: "CEO",
	// 	quote: "Went above and beyond what I was expecting. Such a pleasure to work with",
	// 	rating: 5,
	// },
];
