export const skills = [
	"HTML5",
	"CSS3",
	"JavaScript",
	"React",
	"Redux",
	"Tailwind CSS",
	"TypeScript",
	"Python",
	"Django",
	"Flask",
	"Node.js",
	"REST APIs",
	"SQL",
	"MongoDB",
	"PostgreSql",
	"Git",
	"Docker",
	"AWS",
];

export const skillsData = [
	{
		section: "Languages",
		skills: "Javascript, Python",
	},
	{
		section: "Specialities",
		skills: "React, Redux, Tailwind, Django, Django REST",
	},
	{
		section: "Databases",
		skills: "MySQL, PostgreSQL, MongoDB",
	},
	{
		section: "Deployment",
		skills: "AWS, Azure, Git",
	},
	{
		section: "Design",
		skills: "Figma, Adobe Photoshop",
	},
	{
		section: "Interests",
		skills: "Dogs, Photography, Hiking",
	},
];

export const portfolioData = [
	{
		id: 1,
		title: "The Neo Project",
		img: "neoProject.png",
		shortDescription: "Re-homing Dog Search",
		longDescription: "Search engine for rescue dogs",
		languages: ["Django", "React"],
		keyFeatures: ["Binary search algorithm"],
		link: "https://the-neo-project.web.app",
		linkText: "https://the-neo-project.web.app",
		github: "https://github.com/skies09/the-neo-project",
		additionalGithub: "https://github.com/skies09/neoProject",
	},
	{
		id: 2,
		title: "Donna's Dog Photography",
		img: "donnaDogPhotography.png",
		shortDescription: "Dog Photography Website",
		longDescription: "Website for dog photography business",
		languages: ["React", "Tailwind"],
		keyFeatures: [],
		link: "https://donna-dog-photography.web.app",
		linkText: "https://donna-dog-photography.web.app",
		github: "https://github.com/skies09/donna-dog-photography",
	},

	{
		id: 3,
		title: "Happy Trails",
		img: "happyTrails.png",
		shortDescription: "Dog Walking Website",
		longDescription: "Website for dog walking business",
		languages: ["React", "Tailwind"],
		keyFeatures: [],
		link: "https://happy-trails-457e2.web.app",
		linkText: "https://happy-trails.web.app",
		github: "https://github.com/skies09/happy-trails",
	},
	{
		id: 4,
		title: "All Roads Transport",
		img: "allRoadTransport.png",
		shortDescription: "Driver Hire Website",
		longDescription: "Website for contract driver hire",
		languages: ["React", "Tailwind"],
		keyFeatures: [],
		link: "https://all-roads-transport.web.app",
		linkText: "https://all-roads-transport.web.app",
		github: "https://github.com/skies09/all-roads-transport",
	},
	{
		id: 5,
		title: "Zenith Quest",
		img: "zenithQuest.png",
		shortDescription: "Bullet Journal",
		longDescription: "Diary, bullet journal and mind mapping",
		languages: ["Django", "React"],
		keyFeatures: [],
		// link: "www.zenithquest.co.uk",
		link: "Coming Soon",
		linkText: "Coming Soon",
		github: "",
	},
	// {
	// 	id: 6,
	// 	title: "Pik N Crisp",
	// 	img: "",
	// 	shortDescription: "",
	// 	longDescription: "",
	// 	languages: ["Django", "React"],
	// 	keyFeatures: [],
	// 	link: "Coming Soon",
	// },
];
